#!/bin/sh
source /etc/tekkit-on-demand/config.sh

sign(){
  # Kick package
    echo -en "\xFF"
    # Length
    echo -en "\x00\x23"
    # UTF-16 String: Protocol header
    echo -en "\x00\xA7\x00\x31\x00\x00"
    # Protocol version: 47
    echo -en "\x00\x34\x00\x37\x00\x00"
    # Minecraft version: 
    #                1       .       6        .      4
    #                |               |               |
    echo -en "\x00\x31\x00\x2E\x00\x36\x00\x2E\x00\x34\x00\x00"
    # MOTD: A Minecraft Server
    #echo -n "A Minecraft Server" | sed 's/./\x00\x&'
    # echo -en "\x00\x41\x00\x20\x00\x4D\x00\x69\x00\x6E\x00\x65\x00\x63\x00\x72\x00\x61\x00\x66\x00\x74\x00\x20\x00\x53\x00\x65\x00\x72\x00\x76\x00\x65\x00\x72\x00\x00"
    echo -en "\x00\x55\x00\x70\x00\x20\x00\x69\x00\x6E\x00\x20\x00\x6A\x00\x75\x00\x73\x00\x74\x00\x20\x00\x61\x00\x20\x00\x73\x00\x65\x00\x63\x00\x2E\x00\x2E\x00\x00"
    # Current Players: 
    #                0
    #                |
    echo -en "\x00\x30\x00\x00"
    # Max Players:
    #                20
    #                |
    echo -en "\x00\x32\x00\x30"
#    echo -en "\xFF\x00\x23\x00\xA7\x00"
#    echo -n "$MESSAGE" | sed 's/./\x0&/g'
#    echo -en "\xA7\x00\x30\x00\xA7\x00\x35"
}

if [ ! -f $START_LOCKFILE ]; then
  touch $START_LOCKFILE
  if ! pgrep -U $SERVER_USER -f "$MINECRAFT_JAR" >/dev/null; then
    sudo -u $SERVER_USER -- screen -dmS $SESSION $LAUNCH
    sign
  fi
  /bin/rm $START_LOCKFILE
  exec sudo -u $SERVER_USER nc $LOCAL_IP $LOCAL_PORT
fi
sign
